### ISSUE TITLE
Clean UP & Dockerization eos5qfo

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5qfo#1]

**Comment by GemmaTuron** [comment]
@samuelmaina 

How is this going? any issues so far? Note that I have updated the workflows for this model

**Comment by samuelmaina** [comment]
> @samuelmaina
> 
> How is this going? any issues so far? Note that I have updated the workflows for this model

I am getting a segment fault error for the model when I test on ersilia. I am also getting the same error when I use run.sh. I am checking where there is a lot of memory usage to solve the error.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
The segmentation fault is probably MAC related. Could you start by testing on Codespaces?

**Comment by samuelmaina** [comment]
Hello @GemmaTuron ,
I have been working for sometime now. I was able to resolve the dependency issues by I am having a hard time parsing the output. The model is running with the run.sh  but the ersilia fetch failing with empty output. The output type is flexible list. 
I have logged the output in the main.py and  the fetch log shows the output as 
```
this is the output [['c1cc([C@]2OC[C]3[C]2CO[C@@]3c2ccc3c(c2)OCO3)cc2c1OCO2', 'CC(C)c1ccc2oc3nc(N)c(C(=O)O)cc3c(=O)c2c1', 'CC(C)c1cnn2c(NCc3ccccc3)cc(NC[C@]3CCNC[C@@]3O)nc12', 'CCN(CC)C(=O)c1cccc(C)c1', 'Cc1c(C(=O)Nc2ccc(S(C)(=O)=O)cc2)cn(CCO)c1-c1ccccc1C(F)(F)F', 'Cc1ccc(N2CCN(Cc3nc4ccccc4[nH]3)CC2)cc1C', 'Cc1noc(NS(=O)(=O)c2cccc3c(N(C)C)cccc23)c1C', 'NC1(Cc2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1', 'O=C1CN(NCc2ccc([N+](=O)[O-])o2)C(=O)N1', 'O=C(CCCCC(=O)Nc1c(I)cc(I)c(C(=O)O)c1I)Nc1c(I)cc(I)c(C(=O)O)c1I'], 
['CCCCCCCCCCCCCC(=O)OC(C)C', 'CCOC(=O)c1cnc[nH]1', 'CN(C)C(=O)c1cc2cnc(Nc3ccc(N4CCNCC4)cn3)nc2n1C1CCCC1', 'CN1[C@](CC(=O)c2ccccc2)CCC[C@]1C[C](O)c1ccccc1', 'COc1ccc2[nH]cc(CCNC(C)=O)c2c1', 'CSc1ccc(C(=O)N[C]CCCC[C]NC(=O)CNC(=O)c2cc(C(F)(F)F)ccc2NC(=O)NC(C)C)cc1', 'Cc1noc(C)c1-c1ccc(-c2cc(C(N)=O)c(NC(N)=O)s2)c(O[C]2CCNC2)c1', 'NCCCC[C](NC(=O)[C]1CCCN1C(=O)[C@]1CSSC[C@](N)C(=O)N[C@@](Cc2ccccc2)C(=O)N[C@@](Cc2ccccc2)C(=O)N[C@@](CCC(N)=O)C(=O)N[C@@](CC(N)=O)C(=O)N1)C(=O)NCC(N)=O', 'O=C(Nc1ccc(S(=O)(=O)Nc2ccccc2Cl)c(Cl)c1)c1ccccn1', 'O=C(O)CN1C(=O)c2cccc3cccc(c23)C1=O']]
```
the service.py looks like this
```
            R = []
            for r in reader:
                R += [
                    {"rexgen": [String(x) for x in r]}
                ]  # <-- EDIT: Modify according to type of output (Float, String...)
           meta = {"outcome": h}
           result = {"result": R, "meta": meta}
```
I don't know what I am doing wrong? The whole logs can be found at 

[eos5qfo_cli_fetch.log](https://github.com/ersilia-os/eos5qfo/files/12293395/eos5qfo_cli_fetch.log)

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

I think the issue is still in the dependencies it fails at fetch time but not due to parsing the output as the output is none, as you can see in the log of the error. I'd say the tensorflow version is not the right one?
```
Detailed error:
Model API eos5qfo:run did not produce an outputWARNING:tensorflow:From /opt/conda/envs/eos5qfo/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/core_wln_global/nn.py:20: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/core_wln_global/nn.py:21: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/core_wln_global/directcorefinder.py:103: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2023-08-08 15:59:58.133084: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-08-08 15:59:58.135925: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2445425000 Hz
2023-08-08 15:59:58.136253: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1dd2120 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-08-08 15:59:58.136271: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/rank_diff_wln/directcandranker.py:59: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/rank_diff_wln/directcandranker.py:95: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/codespace/eos/repository/eos5qfo/20230808155936_22C758/eos5qfo/artifacts/framework/code/rexgen_direct/rexgen_direct/rank_diff_wln/directcandranker.py:96: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
```

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
The model is quite old. It was using python 3.6 and it was throwing errors even when all the dependencies had their exact version numbers.  I tried to use tensorflow 2.0 and 1.19 but some functions in the code were not supposed. I then downgraded to tensorflow 1.15 which is working  but with warning. The code is producing a 2D array of smiles with run.sh run and logging the output in the main.py(the one that is being called by run.sh not the one in the native model, I am logging the output array before writing it to the output_file) when fetching hence I am quite sure its the issue with output parsing.

**Comment by samuelmaina** [comment]
Hi @miquelduranfrigola ,
This is the issue that we discussed in the meeting. I have updated the code in my local repo https://github.com/samuelmaina/eos5qfo .

**Comment by GemmaTuron** [comment]
Hi @miquelduranfrigola and @samuelmaina 

I have been able to run the run.sh using simply the dockerfile requirements from the original repo, with Python 3.6 and tensorflow 1.6
I suggest we stick to this and simply refactor the repo structure and work on how the output is given. @samuelmaina can you confirm this works?
Thanks!

**Comment by samuelmaina** [comment]
I was finally able to predict with the standard requirement and the python 3.6. The problem was that the main.py should write the results as json instead of .csv file. The last commit to main.py was to convert the results in json https://github.com/ersilia-os/eos5qfo/commit/49ebcd9e0c4ccb08d85f48282f20c53dfc91030d
